# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Message Sent', 'verbose_name_plural': 'Messages Sent'},
        ),
    ]
